title: RapidQandA
description:
  RapidQandA — the fastest way to create quizzes and lessons from plain old
  text.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
github:
  is_project_page: false
